name: Bazel CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  bazel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bazelisk manually
        run: |
          curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.27.0/bazelisk-linux-amd64 -o bazelisk
          chmod +x bazelisk
          sudo mv bazelisk /usr/local/bin/bazel
          bazel version

      - name: Bazel build
        run: bazel build //bazel:portfolio_greeting

      - name: Bazel test
        run: bazel test //bazel:portfolio_greeting_test
